### PR TITLE
Traslation

### PR DESCRIPTION
**Pull request by Programador-jr**
Portuguese translation files added to bot NQN

### CODE REVIEW

**Comment by Programador-jr** [comment]
There was a word I didn't know the translation "dms", I believe it is "direct message" correct me if I'm wrong.

**Comment by muddyfish** [comment]
DMs are direct messages, yeah^^
If you want to, you can poke me in the support server for the bot to get the tester role, which allows access to where I stick updates

**Comment by Programador-jr** [comment]
Yes, I would love to do that, but what am I going to call you?

**Comment by muddyfish** [comment]
The server's here: https://discord.gg/7K9NgFNE
You can ping me and ask for the role (Blue#6405)

**Pull request closed without merging**
